/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
//import conexionbase.basepro;
import Modelos.DAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author renes
 */
public class interfazbusqueda extends javax.swing.JFrame {

   
    DefaultTableModel model1 =new DefaultTableModel();
   PreparedStatement ps = null;
   Statement st = null;
   ResultSet rs = null;
    Connection cn = DAO.getConexion();
    
    
    public interfazbusqueda() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cmbtipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtbusqueda = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn_Menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTOR-BUSQUEDA");
        setLocation(new java.awt.Point(130, 90));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "nombreProducto", "precioProducto", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleName("BUSCAR");

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1070, 270));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setLayout(new javax.swing.OverlayLayout(jPanel3));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, 1060, 5));

        cmbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Productos", "Clientes", "Empleados", "Movimientos" }));
        jPanel2.add(cmbtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 176, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("BUSCAR:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("SELECCIONE EL TIPO DE BUSQUEDA:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 20));

        txtbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbusquedaKeyPressed(evt);
            }
        });
        jPanel2.add(txtbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 183, -1));

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 30, 10, 100));

        jPanel5.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 10, 100));

        btn_Menu.setBackground(new java.awt.Color(51, 51, 51));
        btn_Menu.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_Menu.setForeground(new java.awt.Color(255, 255, 255));
        btn_Menu.setText("REGRESAR");
        btn_Menu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 102, 0)), "Menu principal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 50, 100, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1107, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Boton para regresar a menu principal
    private void btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuActionPerformed
        // TODO add your handling code here:
        FormMenu op = new FormMenu();
                    op.setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_btn_MenuActionPerformed

    private void txtbusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaKeyPressed
        
        
        String opcion=(String) cmbtipo.getSelectedItem();
        
        //tabla productos
        if("Productos".equals(opcion))
        {
        
        String[] titulos = {"Id", "nombreProducto", "precioProducto","Stock"};
        String[] registros = new String[2000];
        String sql = "SELECT * FROM producto WHERE id LIKE '%" + txtbusqueda.getText() + "%' "
                 + "OR nombreProducto LIKE '%" + txtbusqueda.getText() + "%'"
                /*+ "OR precioProducto LIKE '%" + txtbusqueda.getText() + "%'"
        + "OR Stock LIKE '%" + txtbusqueda.getText() + "%'"*/;
        model1 = new DefaultTableModel(null, titulos);
        Connection conect = DAO.getConexion();
        try
        {
            
           st =  (Statement) conect.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next())
            {
                registros[0] = rs.getString("id");
                registros[1] = rs.getString("nombreProducto");
                registros[2] = rs.getString("precioProducto");
                registros[3] = rs.getString("Stock");
                model1.addRow(registros);
            }
            jTable1.setModel(model1);
        } catch (SQLException ex)
        {
            System.out.println("ERROR AL BUSCAR LOS DATOS : " + ex.getMessage());
        }
        }
        //tabla clientes
        if("Clientes".equals(opcion))
        {
        String[] titulos = {"Id", "nombreCliente", "Dui"};
        String[] registros = new String[2000];
        String sql = "SELECT * FROM clientes WHERE id LIKE '%" + txtbusqueda.getText() + "%' "
                 + "OR nombreCliente LIKE '%" + txtbusqueda.getText() + "%'"
                /*+ "OR dui LIKE '%" + txtbusqueda.getText() + "%'"
        + "OR telefono LIKE '%" + txtbusqueda.getText() + "%'"*/;
        model1 = new DefaultTableModel(null, titulos);
        Connection conect = DAO.getConexion();
        try
        {
            
           st =  (Statement) conect.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next())
            {
                registros[0] = rs.getString("id");
                registros[1] = rs.getString("nombreCliente");
                registros[2] = rs.getString("dui");
                //registros[3] = rs.getString("telefono");
                model1.addRow(registros);
            }
            jTable1.setModel(model1);
        } catch (SQLException ex)
        {
            System.out.println("ERROR AL BUSCAR LOS DATOS : " + ex.getMessage());
        }
        }
        
        //tabla empleados
         if("Empleados".equals(opcion))
        {
        String[] titulos = {"Id", "nombreEmpleado", "Dui"};
        String[] registros = new String[2000];
        String sql = "SELECT * FROM empleados WHERE id LIKE '%" + txtbusqueda.getText() + "%' "
                 + "OR nombreEmpleado LIKE '%" + txtbusqueda.getText() + "%'"
                /*+ "OR dui LIKE '%" + txtbusqueda.getText() + "%'"
        + "OR telefono LIKE '%" + txtbusqueda.getText() + "%'"*/;
        model1 = new DefaultTableModel(null, titulos);
        Connection conect = DAO.getConexion();
        try
        {
            
            st =  (Statement) conect.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next())
            {
                registros[0] = rs.getString("id");
                registros[1] = rs.getString("nombreEmpleado");
                //registros[2] = rs.getString("dui");
                registros[2] = rs.getString("telefono");
                model1.addRow(registros);
            }
            jTable1.setModel(model1);
        } catch (SQLException ex)
        {
            System.out.println("ERROR AL BUSCAR LOS DATOS : " + ex.getMessage());
        }
        }
        //Tabla movimientos
         if("Movimientos".equals(opcion))
        {
        String[] titulos = {"Id", "nombreCliente","nombreVendedor","fechaVenta", "montoTotal","detalleVenta"};
        String[] registros = new String[2000];
        String sql = "SELECT * FROM movimiento WHERE id LIKE '%" + txtbusqueda.getText() + "%' "
                 + "OR nombreCliente LIKE '%" + txtbusqueda.getText() + "%'"
                 + "OR nombreVendedor LIKE '%" + txtbusqueda.getText() + "%'"
                + "OR fechaVenta LIKE '%" + txtbusqueda.getText() + "%'"
                 + "OR montoTotal LIKE '%" + txtbusqueda.getText() + "%'"
                + "OR detalleVenta LIKE '%" + txtbusqueda.getText() + "%'";
        //+ "OR detalleVenta LIKE '%" + txtbusqueda.getText() + "%'";
        model1 = new DefaultTableModel(null, titulos);
        Connection conect = DAO.getConexion();
        try
        {
            
           st =  (Statement) conect.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next())
            {
                registros[0] = rs.getString("id");
                registros[1] = rs.getString("nombreCliente");
                registros[2] = rs.getString("nombreVendedor");
                registros[3] = rs.getString("fechaVenta");
                registros[4] = rs.getString("montoTotal");
                 registros[5] = rs.getString("detalleVenta");
                model1.addRow(registros);
            }
            jTable1.setModel(model1);
        } catch (SQLException ex)
        {
            System.out.println("ERROR AL BUSCAR LOS DATOS : " + ex.getMessage());
        }
        }
            
            }//GEN-LAST:event_txtbusquedaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazbusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazbusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazbusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazbusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazbusqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Menu;
    private javax.swing.JComboBox<String> cmbtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtbusqueda;
    // End of variables declaration//GEN-END:variables
}
