
package Ventanas;

import Modelos.Cliente;
import Modelos.DAO;
import Modelos.DataBase;
import Modelos.Empleado;
import Modelos.Movimientos;
import Modelos.Producto;
import Modelos.Usuarios;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class Ventana_login extends javax.swing.JFrame {
    DAO dao = new DAO();
    Usuarios us = new Usuarios();
    DataBase db = new DataBase();
    Producto prod = new Producto();
    Empleado emp = new Empleado();
    Cliente cli = new Cliente();
    Movimientos mov = new Movimientos();

    /**
     * Creates new form Ventana_login
     */
    public Ventana_login() {
        initComponents();
        this.setResizable(false);
        JOptionPane.showMessageDialog(null,"1. Rodezno Vanegas Balmore Alexander \n2. Carbajal Amaya Ariel Enoc "
                + "\n3. Sánchez Platero Rene Armando\n4. Marroquín Osorio Roberto Francisco ","INREGRANTES",JOptionPane.INFORMATION_MESSAGE);
    }
    
    //METODO PARA VALIDAR TXT VACIOS
     public boolean validar_txtLogin(){
        boolean estado = true;
        String mensaje = "INGRESAR LOS SIGUIENTES DATOS:\n";
        if(txt_Usuario.getText().isEmpty()){
            estado = false;
            mensaje += "> USUARIO\n";    
        }
        if(txt_Clave.getText().isEmpty()){
            estado = false;
            mensaje += "> CLAVE\n";    
        }
        if(!estado){
            JOptionPane.showMessageDialog(null,mensaje,"::===> NO SE PUEDE INICIAR SESION <===::",JOptionPane.ERROR_MESSAGE);
        }
        return estado;
    }
    
    //METODO PARA LIMPIAR TXT
    /*public void Limpiar_txtLogin(){
        txt_Usuario.setText("");
        txt_Clave.setText("");      
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_Usuario = new javax.swing.JTextField();
        btn_Login = new javax.swing.JButton();
        txt_Clave = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USUARIO-LOGIN");
        setLocation(new java.awt.Point(450, 150));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CLAVE");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        txt_Usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsuarioActionPerformed(evt);
            }
        });
        jPanel3.add(txt_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 237, 30));

        btn_Login.setBackground(new java.awt.Color(51, 51, 51));
        btn_Login.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btn_Login.setForeground(new java.awt.Color(255, 255, 255));
        btn_Login.setText("LOGIN");
        btn_Login.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 102, 0)));
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 102, 45));
        jPanel3.add(txt_Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 240, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USUARIO");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 330, 430));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setPreferredSize(new java.awt.Dimension(409, 5));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, -1));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setPreferredSize(new java.awt.Dimension(5, 268));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 20, 5, 190));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        jPanel5.setBackground(new java.awt.Color(153, 102, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(380, 5));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        jPanel6.setBackground(new java.awt.Color(153, 102, 0));
        jPanel6.setPreferredSize(new java.awt.Dimension(5, 268));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //BOTON PARA HACER LOGIN
    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        //validar textos
        //validar_txtLogin();
        
        
        
       
      String usuario = this.txt_Usuario.getText();
      String contra = this.txt_Clave.getText();
        
        Connection conn;
        PreparedStatement ps;
        ResultSet rs;
        
        
        if(validar_txtLogin()){
            
        String sql;
        sql = "select contraseña,nombreUsuario,tipoUsuario from usuarios where nombreUsuario ='"+usuario+"' and contraseña='"+contra+"';";

        try {
            
            Class.forName(db.getDriver());
           
           conn=  DriverManager.getConnection(db.getUrl(),db.getUser(),db.getPassword());
           
           ps = conn.prepareStatement(sql);
           
           
            rs = ps.executeQuery();
            
            if(rs.next()){
                //si existe el usuario
                String u= rs.getString("nombreUsuario");
                String c=rs.getString("contraseña");
                int t= rs.getInt("tipoUsuario");
                us.setTipoUs(t);

                

                if(contra.equals(c)){
                    //frame empleado, admin
                    
                    if(t==1){
                        //frame admin
                        FormMenu o = new FormMenu();
                        o.setVisible(true);
                        JOptionPane.showMessageDialog(null, "Bienvenido: "+this.txt_Usuario.getText(), "ADMINISTRADOR", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    }else if(t==2){
                        //frame empleado
                        MenuEmpleado o = new MenuEmpleado();
                        o.setVisible(true);
                        this.dispose();
                        
                                
                        
                        JOptionPane.showMessageDialog(null, "Bienvenido: "+this.txt_Usuario.getText(), "EMPLEADO", JOptionPane.INFORMATION_MESSAGE);
                       
                    }
                    
                }
            }else{
                //usuario no existe
                JOptionPane.showMessageDialog(null, "El usuario y/o contraseña no existe", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                
        }catch (ClassNotFoundException  | SQLException ex) {
            JOptionPane.showMessageDialog(null,"Informe: "+ex,"ERROR",JOptionPane.ERROR_MESSAGE);
        } 
       
      

           
        }
           
         


       

        //limpiar txt de inicio de sesion
        /*Limpiar_txtLogin();*/
    }//GEN-LAST:event_btn_LoginActionPerformed

    private void txt_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Login;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField txt_Clave;
    private javax.swing.JTextField txt_Usuario;
    // End of variables declaration//GEN-END:variables
}
